### ISSUE TITLE
Where is the installer?

### ISSUE THREAD

**Issue by alexzaytsev-newsroomly** [rvrn22/nmg#3]
I want to download the binary to run the tool. CodePlex downloads don't work and i can't find one off github.

**Comment by rvrn22** [comment]
It's on the releases page.

https://github.com/rvrn22/nmg/releases/download/4.1/NMG.zip

**Comment by RobertoFlores** [comment]
Hi, i want to use some parts of your project to build an ETL, it is possible?

**Comment by rvrn22** [comment]
This project is not really suited for ETL. In my opinion, NHibernate is too slow to be an effective ETL tool.
