### ISSUE TITLE
Tutorial link dead

### ISSUE THREAD

**Issue by atomass** [rvrn22/nmg#6]
Hi,
the tutorial link posted in the documentation wiki page:
http://www.cubrid.org/wiki_apis/entry/using-nmg-nhibernate-mappings-generator-with-cubrid
is wrong and not accessible anymore

Thank you

**Comment by rvrn22** [comment]
It seems to be working again. Might have been a temporary hiccup.

**Comment by atomass** [comment]
Too fast, sorry. I was updating with detailed info.
The wrong link is the one in the Documentation section of the Wiki

**Comment by rvrn22** [comment]
Fixed
