### ISSUE TITLE
Wiki Documentation link dead

### ISSUE THREAD

**Issue by atomass** [rvrn22/nmg#7]
You were super fast to close my previous issue, so here there are the right info about the non-working link:
The tutorial link posted in the documentation wiki page is wrong and not accessible anymore

http://www.cubrid.org/wiki_apis/entry/using-nmg-nhibernate-mappings-generator-with-cubrid 
should be 
http://blog.cubrid.org:8080/wiki_apis/entry/using-nmg-nhibernate-mappings-generator-with-cubrid

Just to let you know,
Thank you

**Comment by rvrn22** [comment]
Fixed
